# Generated by Django 4.1.1 on 2022-10-10 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_feedback_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 17, 13, 41, 884319, tzinfo=datetime.timezone.utc), verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 17, 13, 41, 883320, tzinfo=datetime.timezone.utc), verbose_name='дата'),
        ),
    ]
